stages:
  download:
    cmd: bash data/download.sh
    deps:
      - data/urls.txt
      - data/download.sh
    outs:
      - data/raw/

  decompress:
    cmd: bash data/decompress.sh
    deps:
      - data/raw/
      - data/decompress.sh
    outs:
      - data/interim/

  preprocess:
    cmd: python data/pipelines/main.py
    deps:
      - data/interim
      - data/pipelines/main.py
    outs:
      - data/processed
