defaults:
  # This section can be used if you have multiple config files, 
  # e.g., dev.yaml, prod.yaml, etc. For now, we only have one:
  - override /main: default

# The top-level parameters can be overridden via the CLI.
input_dir: "/path/to/your/input"
output_dir: "/path/to/your/output"
filename_prefix: "POSCAR_"
tc_key: "Tc_OPT"

