# configs/main.yaml

defaults:
  - model: mistral
  - train
  - eval
  - _self_

id_prop_path: "${hydra:runtime.cwd}/data/processed/id_prop.csv"
output_dir: "${hydra:runtime.cwd}/outputs"
model_save_path: "${hydra:runtime.cwd}/outputs/my_model"

prop: tc_ad # tc_ad or tc_opt
chem_info: formula # none, element_list, or formula
id_tag: id

model_source: local # local or hf (Hugging Face)
trainer_type: hf # custom (from AtomGPT) or hf (Hugging Face SFTTrainer)

num_train: 100
num_test: 20
seed_val: 42


