# configs/main.yaml

defaults:
  - mistral   # merges in configs/model/llama.yaml
  - train   # merges in configs/train.yaml
  - eval     # merges in configs/eval.yaml
  - _self_

prop: bandgap
id_tag: jid
chem_info: none
id_prop_path: "atomgpt/examples/inverse_model/id_prop.csv"

output_dir: "./outputs"
model_save_path: "./my_model"

num_train: 100
num_test: 20
seed_val: 42
