# configs/main.yaml

defaults:
  - mistral
  - train
  - eval
  - _self_

id_prop_path: "data/backup_processed"

output_dir: "./outputs"
model_save_path: "./my_model"

num_train: 100
num_test: 20
seed_val: 42
