# src/configs/train.yaml
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 2e-5
num_epochs: 3
warmup_ratio: 0.03
lr_scheduler_type: "cosine"
optim: "adamw_hf"
loss_type: "vanilla"
